import {
  Mail,
  Twitter,
  Type,
  FileText,
  PenTool,
  Camera,
  CheckCircle,
  RefreshCw,
} from "lucide-react";
import { ToolConfig } from "../../../utils/types";

export const toolConfigs: Record<string, ToolConfig> = {
  "email-writer": {
    id: "email-writer",
    title: "Email Writer",
    description:
      "Generate professional emails with customizable tone and purpose",
    icon: <Mail className="h-6 w-6" />,
    inputLabel: "Email Context",
    inputPlaceholder: "Describe what your email should be about...",
    options: [
      { label: "Professional", value: "professional" },
      { label: "Friendly", value: "friendly" },
      { label: "Formal", value: "formal" },
      { label: "Casual", value: "casual" },
    ],
    optionLabel: "Tone",
    aiProviderVisible: true,
  },
  "tweet-generator": {
    id: "tweet-generator",
    title: "Tweet Generator",
    description: "Create engaging tweets with optimal hashtags",
    icon: <Twitter className="h-6 w-6" />,
    inputLabel: "Tweet Topic",
    inputPlaceholder: "Enter your topic or message...",
    options: [
      { label: "Informative", value: "informative" },
      { label: "Humorous", value: "humorous" },
      { label: "Inspirational", value: "inspirational" },
      { label: "Promotional", value: "promotional" },
    ],
    optionLabel: "Style",
    aiProviderVisible: true,
  },
  "grammar-checker": {
    id: "grammar-checker",
    title: "Grammar Checker",
    description: "Fix grammar, spelling, and punctuation errors",
    icon: <CheckCircle className="h-6 w-6" />,
    inputLabel: "Text to Check",
    inputPlaceholder: "Paste your text here...",
    options: [
      { label: "Simple", value: "simple" },
      { label: "Complex", value: "complex" },
      { label: "Technical", value: "technical" },
      { label: "Educational", value: "educational" },
    ],
    optionLabel: "Complexity",
    aiProviderVisible: true,
  },
  "sentence-builder": {
    id: "sentence-builder",
    title: "Sentence Builder",
    description: "Transform ideas into well-structured sentences",
    icon: <Type className="h-6 w-6" />,
    inputLabel: "Ideas or Keywords",
    inputPlaceholder: "Enter ideas or keywords...",
    options: [
      { label: "Simple", value: "simple" },
      { label: "Detailed", value: "detailed" },
      { label: "Academic", value: "academic" },
      { label: "Business", value: "business" },
    ],
    optionLabel: "Complexity",
    aiProviderVisible: true,
  },
  "text-summarizer": {
    id: "text-summarizer",
    title: "Text Summarizer",
    description: "Convert long text into concise summaries",
    icon: <FileText className="h-6 w-6" />,
    inputLabel: "Text to Summarize",
    inputPlaceholder: "Paste the long text...",
    options: [
      { label: "Brief (2-3 sentences)", value: "brief" },
      { label: "Medium (1 paragraph)", value: "medium" },
      { label: "Detailed (2-3 paragraphs)", value: "detailed" },
    ],
    optionLabel: "Summary Length",
    aiProviderVisible: true,
  },
  "content-rewriter": {
    id: "content-rewriter",
    title: "Content Rewriter",
    description: "Rewrite content with different styles and tones",
    icon: <RefreshCw className="h-6 w-6" />,
    inputLabel: "Content to Rewrite",
    inputPlaceholder: "Enter the content...",
    options: [
      { label: "More Professional", value: "professional" },
      { label: "More Casual", value: "casual" },
      { label: "Shorter", value: "shorter" },
      { label: "More Detailed", value: "detailed" },
    ],
    optionLabel: "Rewrite Style",
    aiProviderVisible: true,
  },
  "blog-generator": {
    id: "blog-generator",
    title: "Blog Post Generator",
    description: "Create SEO-optimized blog posts with outlines",
    icon: <PenTool className="h-6 w-6" />,
    inputLabel: "Blog Topic",
    inputPlaceholder: "Enter your blog post topic...",
    options: [
      { label: "How-to Guide", value: "howto" },
      { label: "Listicle", value: "list" },
      { label: "Opinion Piece", value: "opinion" },
      { label: "News/Update", value: "news" },
    ],
    optionLabel: "Post Type",
    aiProviderVisible: true,
  },
  "caption-generator": {
    id: "caption-generator",
    title: "Social Caption Generator",
    description: "Generate engaging captions for social media posts",
    icon: <Camera className="h-6 w-6" />,
    inputLabel: "Post Description",
    inputPlaceholder: "Describe your post...",
    options: [
      { label: "Instagram", value: "instagram" },
      { label: "Facebook", value: "facebook" },
      { label: "LinkedIn", value: "linkedin" },
      { label: "Twitter", value: "twitter" },
    ],
    optionLabel: "Platform",
    aiProviderVisible: true,
  },
};
