import Footer from "@/components/Footer";
import { Badge } from "@/components/ui/badge";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-background">
      {/* Hero Section */}
      <section className="relative px-4 py-10 md:py-14 overflow-hidden">
        <div className="absolute inset-0 bg-grid-slate-100 [mask-image:linear-gradient(0deg,white,rgba(255,255,255,0.6))] dark:bg-grid-slate-700/25 dark:[mask-image:linear-gradient(0deg,rgba(255,255,255,0.1),rgba(255,255,255,0.5))]" />
        <div className="relative max-w-7xl mx-auto text-center space-y-3">
          <Badge
            variant="outline"
            className="mb-2 py-1 px-3 backdrop-blur border-primary/20 bg-primary/5 text-primary"
          >
            📜 Terms of Service
          </Badge>
          <h1 className="text-3xl md:text-5xl font-extrabold tracking-tight bg-gradient-to-r from-gray-900 via-gray-700 to-gray-900 dark:from-white dark:via-gray-200 dark:to-white bg-clip-text text-transparent pb-1">
            Terms of Service
          </h1>
          <p className="text-base md:text-lg text-muted-foreground max-w-2xl mx-auto leading-relaxed">
            Please read these terms carefully before using our services.
          </p>
        </div>
      </section>

      <div className="max-w-7xl mx-auto px-4 py-4 md:py-6 text-foreground">
        <div className="prose prose-gray dark:prose-invert max-w-none space-y-6">
          {/* Introduction */}
          <section>
            <h2 className="text-2xl font-semibold mb-4 text-foreground">
              1. Introduction
            </h2>
            <p className="text-lg text-muted-foreground leading-relaxed">
              Welcome to AI Hub. By accessing or using our website,
              applications, and services, you agree to be bound by these Terms
              of Service. If you do not agree to these terms, please do not use
              our services.
            </p>
          </section>

          {/* Use of Service */}
          <section>
            <h2 className="text-2xl font-semibold mb-4 text-foreground">
              2. Use of Service
            </h2>
            <p className="text-muted-foreground mb-4">
              You agree to use AI Hub only for lawful purposes and in accordance
              with these Terms. You are responsible for:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
              <li>
                Maintaining the confidentiality of your API keys and account
                information.
              </li>
              <li>All activities that occur under your usage or account.</li>
              <li>
                Ensuring your content generation complies with applicable laws
                and regulations.
              </li>
              <li>Respecting the intellectual property rights of others.</li>
            </ul>
          </section>

          {/* API Usage & Liability */}
          <section>
            <h2 className="text-2xl font-semibold mb-4 text-foreground">
              3. AI Providers & API Usage
            </h2>
            <p className="text-muted-foreground mb-4">
              AI Hub acts as an interface to various AI models (OpenAI,
              Anthropic, Google, etc.). We do not control the underlying models
              or their outputs.
            </p>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
              <li>
                The availability and performance of AI models depend on their
                respective providers.
              </li>
              <li>
                You are subject to the terms of service of any third-party AI
                provider you connect to.
              </li>
              <li>
                AI Hub is not liable for any content generated by these
                third-party AI models.
              </li>
            </ul>
          </section>

          {/* User Content */}
          <section>
            <h2 className="text-2xl font-semibold mb-4 text-foreground">
              4. User Content
            </h2>
            <p className="text-muted-foreground">
              We do not claim ownership of the content you generate using AI
              Hub. You retain all rights to your inputs and outputs, subject to
              the terms of the underlying AI providers. We do not store your
              generated content or API keys on our servers.
            </p>
          </section>

          {/* Disclaimer */}
          <section>
            <h2 className="text-2xl font-semibold mb-4 text-foreground">
              5. Disclaimer of Warranties
            </h2>
            <p className="text-muted-foreground">
              AI Hub is provided "as is" and "as available" without any
              warranties of any kind, either express or implied. We do not
              guarantee that the service will be uninterrupted, error-free, or
              completely secure.
            </p>
          </section>

          {/* Changes */}
          <section>
            <h2 className="text-2xl font-semibold mb-4 text-foreground">
              6. Changes to Terms
            </h2>
            <p className="text-muted-foreground">
              We reserve the right to modify these Terms at any time. We will
              notify users of any significant changes by updating the date at
              the top of this page. Your continued use of AI Hub constitutes
              acceptance of the updated Terms.
            </p>
          </section>

          {/* Contact */}
          <section>
            <h2 className="text-2xl font-semibold mb-4 text-foreground">
              7. Contact Us
            </h2>
            <p className="text-muted-foreground">
              If you have any questions about these Terms, please contact us at{" "}
              <a
                href="mailto:ajseven@outlook.in"
                className="text-primary hover:underline"
              >
                ajseven@outlook.in
              </a>
              .
            </p>
          </section>
        </div>

        <div className="mb-6 pt-6 border-border/50 text-sm text-muted-foreground">
          Last Updated:{" "}
          {new Date().toLocaleDateString("en-US", {
            month: "long",
            day: "numeric",
            year: "numeric",
          })}
        </div>
        <Footer />
      </div>
    </div>
  );
}
